### ISSUE TITLE
Isuue regarding Function call in thread_definition.py

### ISSUE THREAD

**Issue by shivaprasadgh** [gruossomonica/LeapMotion_Undistorted_Image_Visualizer#1]
[ WARN:0] videoio(MSMF): OnReadSample() is called with error status: -1072875772
[ WARN:0] videoio(MSMF): async ReadSample() call is failed with error status: -1072875772
[ WARN:1] videoio(MSMF): can't grab frame. Error: -1072875772
Traceback (most recent call last):
  File "C:/Users/shiva/Downloads/LeapMotion_undistorted_Open_CV/LeapMotion_undistorted_image_visualizer-main/leap_camera_control.py", line 94, in <module>
    main()
  File "C:/Users/shiva/Downloads/LeapMotion_undistorted_Open_CV/LeapMotion_undistorted_image_visualizer-main/leap_camera_control.py", line 80, in main
    capture_images(cam, leap, image_visualizer)
  File "C:/Users/shiva/Downloads/LeapMotion_undistorted_Open_CV/LeapMotion_undistorted_image_visualizer-main/leap_camera_control.py", line 33, in capture_images
    left_raw_image, right_raw_image, undistorted_left, undistorted_right = leap.read_images()
  File "C:\Users\shiva\Downloads\LeapMotion_undistorted_Open_CV\LeapMotion_undistorted_image_visualizer-main\thread_definition.py", line 122, in read_images
    return left_raw_image, right_raw_image, undistorted_left, undistorted_right
UnboundLocalError: local variable 'left_raw_image' referenced before assignment

Can you please help me resolve this isuue? Can the video be streamed using Open Cv with same files?

**Comment by gruossomonica** [comment]
Hi, 
There is an error due to the Leap Motion Controller. Images are not recovered or are invalid. 
The left raw image is assigned here:
https://github.com/gruossomonica/LeapMotion_undistorted_image_visualizer/blob/559292a8b39a77b2cd766375d0177c62110dc43f/thread_definition.py#L110-L111

Perhaps the Leap Motion Controller is not working or is not detected.
Please, run the Leap Motion Visualizer to check your device is working properly. This can be found in the Leap Motion Control Panel (more info [here](https://developer.leapmotion.com/desktop-leap-motion-controller/)). If it is working, make sure that the [requirements](https://github.com/gruossomonica/LeapMotion_undistorted_image_visualizer#requirements) are all met. In particular, check the wrapper of the Leap Motion SDK v3 for your Python version is placed in the `lib` folder. This folder path is appended to the system path:
https://github.com/gruossomonica/LeapMotion_undistorted_image_visualizer/blob/559292a8b39a77b2cd766375d0177c62110dc43f/leap_camera_control.py#L1-L2
Please, check your system path.

I followed [this guide](https://developer-archive.leapmotion.com/documentation/python/devguide/Project_Setup.html) to set up the project and test it on Windows 10. I generated the wrapper on my own for the Leap Motion SDK v3 and Python 3.7, as indicated in the readme.
Are you using the same OS, python version, Leap Motion SDK version and wrapper?

**Comment by shivaprasadgh** [comment]
Thank you so much .I am using Windows 10, Python 3.7 version and  SWIG Wrapper for python 3 . But the only problem was regarding the LEAP SDK version. I thought we had to declare global variables earlier for UNBOUND local error,I was clearly wrong.   Your advice actually helped me to get clear images from LEAP sensor.  I followed your instructions and found the solution.

**Comment by gruossomonica** [comment]
Glad to hear you solved it. Good luck with your project!
Then, I'll close this issue.

**Comment by shivaprasadgh** [comment]
Thank you so much for the help  with Leap Sensor and python coding.
